"""empty message

Revision ID: 1e323575c991
Revises: be3bd404bdb1
Create Date: 2024-11-05 00:16:13.662651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '1e323575c991'
down_revision = 'be3bd404bdb1'
branch_labels = None
depends_on = None


def upgrade():
    op.get_bind().execute(text("PRAGMA foreign_keys = ON;"))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_by', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_transcriptions_time_requested'), ['time_requested'], unique=False)
        batch_op.drop_constraint('transcriptions_requestor_fkeyref_users_id', type_='foreignkey')
        batch_op.create_foreign_key("transcriptions_requested_by_fkeyref_users_id", 'users', ['requested_by'], ['id'])
        batch_op.drop_column('requestor')

    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translations_time_requested'), ['time_requested'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translations_time_requested'))

    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requestor', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint("transcriptions_requested_by_fkeyref_users_id", type_='foreignkey')
        batch_op.create_foreign_key('transcriptions_requestor_fkeyref_users_id', 'users', ['requestor'], ['id'])
        batch_op.drop_index(batch_op.f('ix_transcriptions_time_requested'))
        batch_op.drop_column('requested_by')

    # ### end Alembic commands ###
