"""empty message

Revision ID: 5b70af3afed8
Revises: 1e323575c991
Create Date: 2024-12-26 17:35:40.169460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b70af3afed8'
down_revision = '1e323575c991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcripted_text', sa.Text(), nullable=False))
        batch_op.drop_column('transcipted_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcipted_text', sa.TEXT(), nullable=False))
        batch_op.drop_column('transcripted_text')

    # ### end Alembic commands ###
