"""empty message

Revision ID: be3bd404bdb1
Revises: 
Create Date: 2024-10-31 12:30:09.966579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3bd404bdb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=264), nullable=False),
    sa.Column('email_id', sa.String(length=64), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('time_deleted', sa.DateTime(), nullable=True),
    sa.Column('transcriptions', sa.Integer(), nullable=False),
    sa.Column('translations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email_id'), ['email_id'], unique=True)

    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('victim_id', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['victim_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestor', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('transcipted_text', sa.Text(), nullable=False),
    sa.Column('time_requested', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requestor'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('language_from', sa.String(length=16), nullable=False),
    sa.Column('language_to', sa.String(length=16), nullable=False),
    sa.Column('requested_text', sa.String(length=512), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('time_requested', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    op.drop_table('transcriptions')
    op.drop_table('error_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
