"""empty message

Revision ID: 097b17e95551
Revises: 
Create Date: 2024-11-01 12:21:56.954241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097b17e95551'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('jit', sa.Integer(), nullable=True),
    sa.Column('sub', sa.Integer(), nullable=False),
    sa.Column('iat', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('ipa', sa.String(length=15), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('jit'),
    sa.UniqueConstraint('jit')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_family_id'), ['family_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_family_id'))

    op.drop_table('tokens')
    # ### end Alembic commands ###
