"""empty message

Revision ID: 139891a99878
Revises: 5cddb4b516fd
Create Date: 2024-12-14 23:55:15.576127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139891a99878'
down_revision = '5cddb4b516fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jti', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('revoked_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint("ux_tokens_jti", ['jti'])
        batch_op.drop_column('jit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jit', sa.VARCHAR(length=16), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('revoked_at')
        batch_op.drop_column('jti')

    # ### end Alembic commands ###
