"""empty message

Revision ID: 5cddb4b516fd
Revises: 097b17e95551
Create Date: 2024-11-08 20:07:48.742981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cddb4b516fd'
down_revision = '097b17e95551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('jit',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('jit',
               existing_type=sa.String(length=16),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
